## Airbnb Python(pandas) Project

### Import Libraries

In [107]:
import pandas as pd

### Load the dataset

In [5]:
df = pd.read_csv("D:/NH projects/Data Cleaning Python/airbnb.csv")

### Display the first 5 rows

In [6]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1.312228e+06,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.683710,-73.964610,Private room,55.0,...,20/12/15,0.03,1.0,0.0,0.0,No License,5,1,1,Not specified
1,4.527754e+07,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144.0,...,01/05/23,0.24,139.0,364.0,2.0,No License,4.67,2,1,1
2,9.710000e+17,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187.0,...,18/12/23,1.67,1.0,343.0,6.0,Exempt,4.17,1,2,1
3,3.857863e+06,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120.0,...,17/09/23,1.38,2.0,363.0,12.0,No License,4.64,1,1,1
4,4.089661e+07,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85.0,...,03/12/23,0.24,133.0,335.0,3.0,No License,4.91,Studio,1,1

### Display the last 5 rows

In [7]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
20765,2.473690e+07,Rental unit in New York · ★4.75 · 1 bedroom · ...,186680487,Henry D,Manhattan,Lower East Side,40.711380,-73.991560,Private room,45.0,...,29/09/23,1.81,1.0,157.0,12.0,No License,4.75,1,1,1
20766,2.835711e+06,Rental unit in New York · ★4.46 · 1 bedroom · ...,3237504,Aspen,Manhattan,Greenwich Village,40.730580,-74.000700,Entire home/apt,105.0,...,01/07/23,0.48,1.0,0.0,1.0,No License,4.46,1,2,1
20767,5.182527e+07,Rental unit in New York · ★4.93 · 1 bedroom · ...,304317395,Jeff,Manhattan,Hell's Kitchen,40.757350,-73.993430,Entire home/apt,299.0,...,08/12/23,2.09,1.0,0.0,27.0,No License,4.93,1,1,1
20768,7.830000e+17,Rental unit in New York · ★5.0 · 1 bedroom · 1...,163083101,Marissa,Manhattan,Chinatown,40.713750,-73.991470,Entire home/apt,115.0,...,17/09/23,0.91,1.0,363.0,7.0,No License,5,1,1,1
20769,5.660000e+17,Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...,93827372,Glenroy,Queens,Rosedale,40.658874,-73.728651,Private room,102.0,...,10/12/23,4.50,1.0,0.0,62.0,OSE-STRREG-0000513,4.89,1,1,1

### What are the dimensions of the dataset ?

In [44]:
print(f"Rows: {df.shape[0]} , Columns: {df.shape[1]}")

Rows: 20724 , Columns: 22

### Give a concise summary of the df

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20770 entries, 0 to 20769
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              20770 non-null  float64
 1   name                            20770 non-null  str
 2   host_id                         20770 non-null  int64
 3   host_name                       20770 non-null  str
 4   neighbourhood_group             20770 non-null  str
 5   neighbourhood                   20763 non-null  str
 6   latitude                        20763 non-null  float64
 7   longitude                       20763 non-null  float64
 8   room_type                       20763 non-null  str
 9   price                           20736 non-null  float64
 10  minimum_nights                  20763 non-null  float64
 11  number_of_reviews               20763 non-null  float64
 12  last_review                     20763 non-null  str
 13  reviews_per_month               20763 non-null  float64
 14  calculated_host_listings_count  20763 non-null  float64
 15  availability_365                20763 non-null  float64
 16  number_of_reviews_ltm           20763 non-null  float64
 17  license                         20770 non-null  str
 18  rating                          20770 non-null  str
 19  bedrooms                        20770 non-null  str
 20  beds                            20770 non-null  int64
 21  baths                           20770 non-null  str
dtypes: float64(10), int64(2), str(10)
memory usage: 3.5 MB

### Statistics summary for the df

In [14]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,beds
count,2.077000e+04,2.077000e+04,20763.000000,20763.000000,20736.000000,20763.000000,20763.000000,20763.000000,20763.000000,20763.000000,20763.000000,20770.000000
mean,3.033858e+17,1.749049e+08,40.726821,-73.939179,187.714940,28.558493,42.610605,1.257589,18.866686,206.067957,10.848962,1.723592
std,3.901221e+17,1.725657e+08,0.060293,0.061403,1023.245124,33.532697,73.523401,1.904472,70.921443,135.077259,21.354876,1.211993
min,2.595000e+03,1.678000e+03,40.500314,-74.249840,10.000000,1.000000,1.000000,0.010000,1.000000,0.000000,0.000000,1.000000
25%,2.707260e+07,2.041184e+07,40.684159,-73.980755,80.000000,30.000000,4.000000,0.210000,1.000000,87.000000,1.000000,1.000000
50%,4.992852e+07,1.086990e+08,40.722890,-73.949597,125.000000,30.000000,14.000000,0.650000,2.000000,215.000000,3.000000,1.000000
75%,7.220000e+17,3.143997e+08,40.763106,-73.917475,199.000000,30.000000,49.000000,1.800000,5.000000,353.000000,15.000000,2.000000
max,1.050000e+18,5.504035e+08,40.911147,-73.713650,100000.000000,1250.000000,1865.000000,75.490000,713.000000,365.000000,1075.000000,42.000000

### Missing values in each column

In [15]:
df.isnull().sum()

id                                 0
name                               0
host_id                            0
host_name                          0
neighbourhood_group                0
neighbourhood                      7
latitude                           7
longitude                          7
room_type                          7
price                             34
minimum_nights                     7
number_of_reviews                  7
last_review                        7
reviews_per_month                  7
calculated_host_listings_count     7
availability_365                   7
number_of_reviews_ltm              7
license                            0
rating                             0
bedrooms                           0
beds                               0
baths                              0
dtype: int64

### Drop missing values

In [19]:
df.dropna(inplace = True)

In [21]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
license                           0
rating                            0
bedrooms                          0
beds                              0
baths                             0
dtype: int64

### Check duplicate rows

In [23]:
df.duplicated().sum()

np.int64(12)

### See duplicate rows

In [26]:
df[df.duplicated()]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
6,4.527754e+07,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144.0,...,01/05/23,0.24,139.0,364.0,2.0,No License,4.67,2,1,1
7,9.710000e+17,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187.0,...,18/12/23,1.67,1.0,343.0,6.0,Exempt,4.17,1,2,1
8,3.857863e+06,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120.0,...,17/09/23,1.38,2.0,363.0,12.0,No License,4.64,1,1,1
9,4.089661e+07,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85.0,...,03/12/23,0.24,133.0,335.0,3.0,No License,4.91,Studio,1,1
10,4.958498e+07,Rental unit in New York · ★5.0 · 1 bedroom · 1...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.759950,-73.992960,Entire home/apt,115.0,...,29/07/23,0.16,139.0,276.0,2.0,No License,5,1,1,1
20736,7.990000e+17,Rental unit in New York · 2 bedrooms · 2 beds ...,224733902,CozySuites Copake,Manhattan,Upper East Side,40.768970,-73.957592,Entire home/apt,153.0,...,15/09/23,0.41,8.0,308.0,2.0,No License,No rating,2,2,2
20737,5.930000e+17,Rental unit in New York · ★4.79 · 2 bedrooms ·...,23219783,Rob,Manhattan,West Village,40.730220,-74.002910,Entire home/apt,175.0,...,22/11/23,2.03,4.0,129.0,25.0,No License,4.79,2,2,1
20738,9.230000e+17,Loft in New York · ★4.33 · 1 bedroom · 2 beds ...,520265731,Rodrigo,Manhattan,Greenwich Village,40.728390,-73.999540,Entire home/apt,156.0,...,02/01/24,2.60,1.0,356.0,9.0,Exempt,4.33,1,2,1
20739,1.336161e+07,Rental unit in New York · ★4.89 · 2 bedrooms ·...,8961407,Jamie,Manhattan,Harlem,40.805700,-73.946250,Entire home/apt,397.0,...,08/09/23,1.08,3.0,274.0,3.0,No License,4.89,2,2,1
20740,5.119566e+07,Rental unit in New York · Studio · 1 bed · 1 bath,51501835,Jeniffer,Manhattan,Chinatown,40.718360,-73.995850,Entire home/apt,100.0,...,25/05/23,0.08,139.0,306.0,1.0,No License,No rating,Studio,1,1
20741,2.523473e+07,Rental unit in New York · ★4.41 · 1 bedroom · ...,1497427,Mara,Manhattan,Upper East Side,40.774030,-73.950580,Entire home/apt,120.0,...,31/03/23,0.26,2.0,364.0,1.0,No License,4.41,1,2,1
20742,3.339399e+06,Rental unit in New York · ★4.73 · 1 bedroom · ...,2119276,Urban Furnished,Manhattan,West Village,40.732030,-74.006760,Entire home/apt,143.0,...,09/05/23,0.20,54.0,285.0,2.0,No License,4.73,1,1,1

### Delete duplicate rows

In [30]:
df.drop_duplicates(inplace=True)

### Check data types

In [32]:
df.dtypes

id                                float64
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                 float64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count    float64
availability_365                  float64
number_of_reviews_ltm             float64
license                               str
rating                                str
bedrooms                              str
beds                                int64
baths                                 str
dtype: object

### Type casting

In [36]:
df['id'] = df['id'].astype(object)
df.dtypes

id                                 object
name                                  str
host_id                             int64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                 float64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count    float64
availability_365                  float64
number_of_reviews_ltm             float64
license                               str
rating                                str
bedrooms                              str
beds                                int64
baths                                 str
dtype: object

In [37]:
df['host_id'] = df['host_id'].astype(object)
df.dtypes

id                                 object
name                                  str
host_id                            object
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                 float64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count    float64
availability_365                  float64
number_of_reviews_ltm             float64
license                               str
rating                                str
bedrooms                              str
beds                                int64
baths                                 str
dtype: object

In [89]:
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

### What are the unique 'neighbourhood_group' values in New York?

In [45]:
df['neighbourhood_group'].unique()

<StringArray>
['Brooklyn', 'Manhattan', 'Queens', 'Bronx', 'Staten Island']
Length: 5, dtype: str

### How many listings are there in each 'neighbourhood_group'?

In [46]:
df['neighbourhood_group'].value_counts()

neighbourhood_group
Manhattan        8031
Brooklyn         7694
Queens           3759
Bronx             949
Staten Island     291
Name: count, dtype: int64

### What is the average price of listings in each 'neighbourhood_group'?

In [49]:
df.groupby('neighbourhood_group')['price'].mean().sort_values(ascending=False)

neighbourhood_group
Manhattan        227.585979
Brooklyn         187.196647
Queens           126.521415
Staten Island    118.780069
Bronx            118.407798
Name: price, dtype: float64

### Find the top 5 most expensive listings

In [59]:
df.nlargest(5, 'price')[['name', 'neighbourhood_group', 'price']]

,name,neighbourhood_group,price
3995,Rental unit in Brooklyn · ★4.48 · 1 bedroom · ...,Brooklyn,100000.0
5497,Rental unit in Brooklyn · ★4.33 · 1 bedroom · ...,Brooklyn,100000.0
906,Boutique hotel in New York · 1 bedroom · 1 bed...,Manhattan,10000.0
2957,Rental unit in Queens · ★4.14 · 2 bedrooms · 2...,Queens,10000.0
3031,Loft in New York · ★4.50 · 4 bedrooms · 5 beds...,Manhattan,10000.0

### Filter listings that cost more than $500 and have over 50 reviews

In [67]:
expensive_popular = df[(df['price'] > 500) & (df['number_of_reviews_ltm'] < 50)]
expensive_popular.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
20,29923599.0,Serviced apartment in New York City · Studio ·...,220229838,Chamber Hotel,Manhattan,Midtown,40.761760,-73.976590,Hotel room,1000.0,...,02/07/19,0.02,10.0,363.0,0.0,Exempt,No rating,Studio,2,1
54,1146653.0,Condo in New York · ★4.90 · 2 bedrooms · 1 bed...,836168,Henry,Manhattan,Upper West Side,40.792960,-73.964990,Entire home/apt,1000.0,...,27/01/16,0.18,10.0,364.0,0.0,No License,4.9,2,1,1
69,807000000000000000.0,Home in Queens · ★4.50 · 6 bedrooms · 8 beds ·...,496749638,B,Queens,South Ozone Park,40.664932,-73.815531,Entire home/apt,900.0,...,13/10/23,1.40,2.0,365.0,14.0,No License,4.5,6,8,4
70,49124837.0,Hotel in New York · ★4.80 · Studio · 1 bed · 1...,383332265,Tyler,Manhattan,Chelsea,40.747660,-73.992270,Private room,999.0,...,22/09/21,0.31,9.0,0.0,0.0,Exempt,4.8,Studio,1,1
169,803000000000000000.0,Rental unit in New York · ★5.0 · 3 bedrooms · ...,66989673,Theresa,Manhattan,Upper East Side,40.778106,-73.954309,Entire home/apt,950.0,...,04/12/23,0.76,1.0,364.0,7.0,No License,5,3,3,3

### Which 'room_type' is the most common?

In [71]:
df['room_type'].value_counts()

room_type
Entire home/apt    11530
Private room        8791
Shared room          291
Hotel room           112
Name: count, dtype: int64

### Find the listing with the maximum number of reviews

In [73]:
max_rvw_idx = df['number_of_reviews'].idxmax()
max_rvw_idx

np.int64(2389)

### Create a new column 'min_revenue' (price * minimum_nights)

In [80]:
df['min_revenue'] = df['price'] * df['minimum_nights']
df[['name', 'price', 'minimum_nights', 'min_revenue']].head()

,name,price,minimum_nights,min_revenue
0,Rental unit in Brooklyn · ★5.0 · 1 bedroom,55.0,30.0,1650.0
1,Rental unit in New York · ★4.67 · 2 bedrooms ·...,144.0,30.0,4320.0
2,Rental unit in New York · ★4.17 · 1 bedroom · ...,187.0,2.0,374.0
3,Rental unit in New York · ★4.64 · 1 bedroom · ...,120.0,30.0,3600.0
4,Condo in New York · ★4.91 · Studio · 1 bed · 1...,85.0,30.0,2550.0

### Find the average price and minimum nights for each 'room_type'

In [105]:
df.groupby('room_type').agg(avg_price = ('price', 'mean'), min_nights = ('minimum_nights' , 'min'))

                  avg_price  min_nights
room_type
Entire home/apt  223.025152         1.0
Hotel room       415.053571         1.0
Private room     139.574792         1.0
Shared room      156.680412         1.0

### Top 10 hosts with the most listings

In [85]:
df.groupby('host_name')['calculated_host_listings_count'].max().sort_values(ascending=False).head(10)

host_name
Blueground            713.0
Eugene                589.0
June                  348.0
Hiroki                267.0
RoomPicks             259.0
Urban Furnished       256.0
Shogo                 249.0
Momoyo                236.0
Reservations          201.0
Furnished Quarters    164.0
Name: calculated_host_listings_count, dtype: float64

### Find all listings in a specific neighborhood, like 'Chelsea'

In [90]:
chelsea_listings = df[df['neighbourhood'] == 'Chelsea']
print(f"Total listings in Chelsea: {len(chelsea_listings)}")

Total listings in Chelsea: 365

### Calculate the correlation between price, reviews, and availability

In [91]:
df[['price', 'number_of_reviews', 'availability_365']].corr()

                      price  number_of_reviews  availability_365
price              1.000000          -0.012616          0.020123
number_of_reviews -0.012616           1.000000         -0.050150
availability_365   0.020123          -0.050150          1.000000

### Drop the 'license' column

In [98]:
df.drop(columns=['license'], inplace = True)

In [99]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'rating', 'bedrooms',
       'beds', 'baths', 'min_revenue', 'average_price'],
      dtype='str')

### Find the cheapest listing in each 'neighbourhood_group'

In [101]:
df.groupby('neighbourhood_group')['price'].min().sort_values(ascending = True)

neighbourhood_group
Brooklyn         10.0
Manhattan        10.0
Queens           17.0
Bronx            24.0
Staten Island    33.0
Name: price, dtype: float64

### Save processed data to a new CSV file

In [106]:
df.to_csv('airbnb_processed.csv', index=False)